-- Initial game balance for an empty database. Review before applying.
SET NAMES utf8mb4;
INSERT INTO game_db.monstertypes (`monsterType`, `name`, `level`, `maxHP`, `experience`, `attackPower`, `aggressive`, `detectionRange`, `attackRange`, `moveSpeed`, `attackIntervalMs`, `canWander`, `canChase`, `canAttack`, `idleMinTimeMs`, `idleMaxTimeMs`, `wanderMinTimeMs`, `wanderMaxTimeMs`, `wanderRadius`, `maxAggroRange`, `respawnRadius`, `respawnDelayMs`) VALUES (0, CONVERT(0x47686F7374 USING utf8mb4), 1, 90, 12, 25, 0, 5, 1.5, 3, 2000, 1, 1, 1, 4000, 8000, 6000, 10000, 3, 30, 2, 5000);
INSERT INTO game_db.monstertypes (`monsterType`, `name`, `level`, `maxHP`, `experience`, `attackPower`, `aggressive`, `detectionRange`, `attackRange`, `moveSpeed`, `attackIntervalMs`, `canWander`, `canChase`, `canAttack`, `idleMinTimeMs`, `idleMaxTimeMs`, `wanderMinTimeMs`, `wanderMaxTimeMs`, `wanderRadius`, `maxAggroRange`, `respawnRadius`, `respawnDelayMs`) VALUES (1, CONVERT(0x4C697A617264 USING utf8mb4), 6, 260, 180, 17, 0, 6, 1.6, 4.2, 2000, 1, 1, 1, 4000, 8000, 6000, 10000, 4, 30, 1.5, 6000);
INSERT INTO game_db.monstertypes (`monsterType`, `name`, `level`, `maxHP`, `experience`, `attackPower`, `aggressive`, `detectionRange`, `attackRange`, `moveSpeed`, `attackIntervalMs`, `canWander`, `canChase`, `canAttack`, `idleMinTimeMs`, `idleMaxTimeMs`, `wanderMinTimeMs`, `wanderMaxTimeMs`, `wanderRadius`, `maxAggroRange`, `respawnRadius`, `respawnDelayMs`) VALUES (2, CONVERT(0x4B6E69676874 USING utf8mb4), 4, 260, 38, 13, 1, 7, 2, 2.8, 2500, 1, 1, 1, 4000, 8000, 6000, 10000, 3, 30, 2, 8000);
INSERT INTO game_db.monstertypes (`monsterType`, `name`, `level`, `maxHP`, `experience`, `attackPower`, `aggressive`, `detectionRange`, `attackRange`, `moveSpeed`, `attackIntervalMs`, `canWander`, `canChase`, `canAttack`, `idleMinTimeMs`, `idleMaxTimeMs`, `wanderMinTimeMs`, `wanderMaxTimeMs`, `wanderRadius`, `maxAggroRange`, `respawnRadius`, `respawnDelayMs`) VALUES (3, CONVERT(0x526174 USING utf8mb4), 1, 90, 60, 7, 0, 6, 1.6, 4, 2200, 1, 1, 1, 4000, 8000, 6000, 10000, 3, 30, 1.5, 5000);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 1, 100, 300);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 2, 400, 330);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 3, 900, 360);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 4, 1600, 390);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 5, 2500, 420);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 6, 3600, 450);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 7, 4900, 480);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 8, 6400, 510);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 9, 8100, 540);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 10, 10000, 570);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 11, 12100, 600);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 12, 14400, 630);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 13, 16900, 660);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 14, 19600, 690);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 15, 22500, 720);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 16, 25600, 750);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 17, 28900, 780);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 18, 32400, 810);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 19, 36100, 840);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (0, 20, 0, 870);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 1, 100, 240);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 2, 400, 264);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 3, 900, 288);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 4, 1600, 312);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 5, 2500, 336);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 6, 3600, 360);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 7, 4900, 384);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 8, 6400, 408);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 9, 8100, 432);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 10, 10000, 456);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 11, 12100, 480);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 12, 14400, 504);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 13, 16900, 528);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 14, 19600, 552);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 15, 22500, 576);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 16, 25600, 600);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 17, 28900, 624);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 18, 32400, 648);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 19, 36100, 672);
INSERT INTO game_db.playerlevelstats (`class`, `level`, `requiredExperience`, `maxHP`) VALUES (1, 20, 0, 696);
