ALTER TABLE MonsterTypes
    ADD COLUMN canWander TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER attackIntervalMs,
    ADD COLUMN canChase TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER canWander,
    ADD COLUMN canAttack TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER canChase,
    ADD COLUMN idleMinTimeMs BIGINT UNSIGNED NOT NULL DEFAULT 1000 AFTER canAttack,
    ADD COLUMN idleMaxTimeMs BIGINT UNSIGNED NOT NULL DEFAULT 3000 AFTER idleMinTimeMs,
    ADD COLUMN wanderMinTimeMs BIGINT UNSIGNED NOT NULL DEFAULT 2000 AFTER idleMaxTimeMs,
    ADD COLUMN wanderMaxTimeMs BIGINT UNSIGNED NOT NULL DEFAULT 5000 AFTER wanderMinTimeMs;
